yay -S acl
yay -S adobe-source-code-pro-fonts
yay -S adwaita-cursors
yay -S adwaita-icon-theme
yay -S alsa-card-profiles
yay -S alsa-lib
yay -S alsa-topology-conf
yay -S alsa-ucm-conf
yay -S amd-ucode
yay -S aom
yay -S archlinux-keyring
yay -S argon2
yay -S at-spi2-core
yay -S atkmm
yay -S attr
yay -S audiofile
yay -S audit
yay -S autoconf
yay -S automake
yay -S avahi
yay -S base
yay -S base-devel
yay -S bash
yay -S betterdiscord-installer
yay -S binutils
yay -S bison
yay -S bluez-libs
yay -S boost-libs
yay -S brotli
yay -S btop
yay -S bubblewrap
yay -S bzip2
yay -S c-ares
yay -S ca-certificates
yay -S ca-certificates-mozilla
yay -S ca-certificates-utils
yay -S cairo
yay -S cairomm
yay -S cantarell-fonts
yay -S chromaprint
yay -S chrono-date
yay -S coreutils
yay -S cronie
yay -S cryptsetup
yay -S curl
yay -S dav1d
yay -S db
yay -S db5.3
yay -S dbus
yay -S dconf
yay -S debugedit
yay -S default-cursors
yay -S desktop-file-utils
yay -S device-mapper
yay -S diffutils
yay -S discord
yay -S dnssec-anchors
yay -S double-conversion
yay -S duktape
yay -S e2fsprogs
yay -S efibootmgr
yay -S efivar
yay -S electron
yay -S electron25
yay -S enchant
yay -S expat
yay -S faad2
yay -S fakeroot
yay -S ffmpeg
yay -S fftw
yay -S file
yay -S filesystem
yay -S findutils
yay -S flac
yay -S flex
yay -S fluidsynth
yay -S fmt
yay -S font-manager
yay -S fontconfig
yay -S freetype2
yay -S fribidi
yay -S fuse-common
yay -S fuse2
yay -S fuse3
yay -S gawk
yay -S gc
yay -S gcc
yay -S gcc-libs
yay -S gdbm
yay -S gdk-pixbuf2
yay -S gettext
yay -S giflib
yay -S git
yay -S glib-networking
yay -S glib2
yay -S glibc
yay -S glibmm
yay -S glslang
yay -S gmp
yay -S gnupg
yay -S gnutls
yay -S go
yay -S google-chrome
yay -S gperftools
yay -S gpgme
yay -S gpm
yay -S graphite
yay -S grep
yay -S groff
yay -S gsettings-desktop-schemas
yay -S gsm
yay -S gssdp
yay -S gst-plugin-pipewire
yay -S gst-plugins-bad-libs
yay -S gst-plugins-base-libs
yay -S gstreamer
yay -S gtk-layer-shell
yay -S gtk-update-icon-cache
yay -S gtk3
yay -S gtkmm3
yay -S guile
yay -S gupnp
yay -S gupnp-igd
yay -S gzip
yay -S harfbuzz
yay -S harfbuzz-icu
yay -S hicolor-icon-theme
yay -S hidapi
yay -S highway
yay -S hwdata
yay -S hwloc
yay -S hyphen
yay -S hyprland
yay -S hyprpaper-git
yay -S iana-etc
yay -S icu
yay -S imath
yay -S iproute2
yay -S iptables
yay -S iputils
yay -S iso-codes
yay -S jansson
yay -S json-c
yay -S json-glib
yay -S jsoncpp
yay -S kbd
yay -S keyutils
yay -S kitty
yay -S kitty-shell-integration
yay -S kitty-terminfo
yay -S kmod
yay -S krb5
yay -S l-smash
yay -S lame
yay -S lcms2
yay -S ldns
yay -S less
yay -S lf
yay -S lib32-acl
yay -S lib32-brotli
yay -S lib32-bzip2
yay -S lib32-dbus
yay -S lib32-e2fsprogs
yay -S lib32-expat
yay -S lib32-fontconfig
yay -S lib32-freetype2
yay -S lib32-gcc-libs
yay -S lib32-gettext
yay -S lib32-glib2
yay -S lib32-glibc
yay -S lib32-harfbuzz
yay -S lib32-keyutils
yay -S lib32-krb5
yay -S lib32-libcap
yay -S lib32-libffi
yay -S lib32-libgcrypt
yay -S lib32-libgpg-error
yay -S lib32-libldap
yay -S lib32-libnl
yay -S lib32-libpcap
yay -S lib32-libpng
yay -S lib32-libtirpc
yay -S lib32-libx11
yay -S lib32-libxau
yay -S lib32-libxcb
yay -S lib32-libxcrypt
yay -S lib32-libxcursor
yay -S lib32-libxdmcp
yay -S lib32-libxext
yay -S lib32-libxfixes
yay -S lib32-libxi
yay -S lib32-libxrandr
yay -S lib32-libxrender
yay -S lib32-openssl
yay -S lib32-pam
yay -S lib32-pcre2
yay -S lib32-systemd
yay -S lib32-util-linux
yay -S lib32-xz
yay -S lib32-zlib
yay -S lib32-zstd
yay -S libao
yay -S libappindicator-gtk3
yay -S libarchive
yay -S libass
yay -S libassuan
yay -S libasyncns
yay -S libavc1394
yay -S libavif
yay -S libbluray
yay -S libbpf
yay -S libbs2b
yay -S libbsd
yay -S libcamera
yay -S libcamera-ipa
yay -S libcap
yay -S libcap-ng
yay -S libcdio
yay -S libcdio-paranoia
yay -S libcloudproviders
yay -S libcolord
yay -S libcups
yay -S libdaemon
yay -S libdatrie
yay -S libdbusmenu-glib
yay -S libdbusmenu-gtk3
yay -S libdisplay-info
yay -S libdrm
yay -S libedit
yay -S libelf
yay -S libepoxy
yay -S libevdev
yay -S libevent
yay -S libfdk-aac
yay -S libffi
yay -S libfontenc
yay -S libfreeaptx
yay -S libgcrypt
yay -S libglvnd
yay -S libgme
yay -S libgpg-error
yay -S libgudev
yay -S libice
yay -S libid3tag
yay -S libidn2
yay -S libiec61883
yay -S libimobiledevice
yay -S libinput
yay -S libinstpatch
yay -S libisl
yay -S libjpeg-turbo
yay -S libjxl
yay -S libksba
yay -S liblc3
yay -S libldac
yay -S libldap
yay -S libliftoff
yay -S libmad
yay -S libmanette
yay -S libmd
yay -S libmfx
yay -S libmikmod
yay -S libmm-glib
yay -S libmms
yay -S libmnl
yay -S libmodplug
yay -S libmpc
yay -S libmpcdec
yay -S libmpdclient
yay -S libmysofa
yay -S libndp
yay -S libnetfilter_conntrack
yay -S libnewt
yay -S libnfnetlink
yay -S libnfs
yay -S libnftnl
yay -S libnghttp2
yay -S libnice
yay -S libnl
yay -S libnm
yay -S libnotify
yay -S libnsl
yay -S libogg
yay -S libomxil-bellagio
yay -S libopenmpt
yay -S libp11-kit
yay -S libpcap
yay -S libpciaccess
yay -S libpgm
yay -S libpipewire
yay -S libplist
yay -S libpng
yay -S libproxy
yay -S libpsl
yay -S libpulse
yay -S libraw1394
yay -S librsvg
yay -S librsync
yay -S libsamplerate
yay -S libsasl
yay -S libseccomp
yay -S libsecret
yay -S libshout
yay -S libsidplayfp
yay -S libsigc++
yay -S libsm
yay -S libsndfile
yay -S libsodium
yay -S libsoup
yay -S libsoup3
yay -S libsoxr
yay -S libssh
yay -S libssh2
yay -S libstemmer
yay -S libsysprof-capture
yay -S libtasn1
yay -S libteam
yay -S libthai
yay -S libtheora
yay -S libtiff
yay -S libtirpc
yay -S libtool
yay -S libunistring
yay -S libunwind
yay -S libupnp
yay -S liburing
yay -S libusb
yay -S libusbmuxd
yay -S libutempter
yay -S libva
yay -S libvdpau
yay -S libverto
yay -S libvorbis
yay -S libvpx
yay -S libwacom
yay -S libwebp
yay -S libwireplumber
yay -S libwpe
yay -S libx11
yay -S libxau
yay -S libxcb
yay -S libxcomposite
yay -S libxcrypt
yay -S libxcursor
yay -S libxcvt
yay -S libxdamage
yay -S libxdg-basedir
yay -S libxdmcp
yay -S libxext
yay -S libxfixes
yay -S libxfont2
yay -S libxft
yay -S libxi
yay -S libxinerama
yay -S libxkbcommon
yay -S libxkbcommon-x11
yay -S libxkbfile
yay -S libxml2
yay -S libxmu
yay -S libxrandr
yay -S libxrender
yay -S libxshmfence
yay -S libxslt
yay -S libxss
yay -S libxt
yay -S libxtst
yay -S libxv
yay -S libxxf86vm
yay -S libyaml
yay -S libyuv
yay -S licenses
yay -S lilv
yay -S linux
yay -S linux-api-headers
yay -S linux-firmware
yay -S linux-firmware-whence
yay -S llvm-libs
yay -S lm_sensors
yay -S lsof
yay -S lua
yay -S lv2
yay -S lz4
yay -S lzo
yay -S m4
yay -S make
yay -S md4c
yay -S mesa
yay -S minizip
yay -S mkinitcpio
yay -S mkinitcpio-busybox
yay -S mobile-broadband-provider-info
yay -S mpc
yay -S mpd
yay -S mpfr
yay -S mpg123
yay -S mtdev
yay -S nano
yay -S ncmpcpp
yay -S ncurses
yay -S neofetch
yay -S nettle
yay -S networkmanager
yay -S npth
yay -S nspr
yay -S nss
yay -S obsidian
yay -S ocl-icd
yay -S openal
yay -S opencore-amr
yay -S openexr
yay -S openjpeg2
yay -S openmpi
yay -S openpmix
yay -S openssh
yay -S openssl
yay -S opus
yay -S orc
yay -S p11-kit
yay -S pacman
yay -S pacman-mirrorlist
yay -S pam
yay -S pambase
yay -S pango
yay -S pangomm
yay -S patch
yay -S pciutils
yay -S pcre
yay -S pcre2
yay -S pcsclite
yay -S perl
yay -S perl-error
yay -S perl-mailtools
yay -S perl-timedate
yay -S pinentry
yay -S pipewire
yay -S pipewire-alsa
yay -S pipewire-audio
yay -S pipewire-jack
yay -S pipewire-pulse
yay -S pixman
yay -S pkgconf
yay -S playerctl
yay -S polkit
yay -S popt
yay -S portaudio
yay -S procps-ng
yay -S psmisc
yay -S python
yay -S qt5-base
yay -S qt5-declarative
yay -S qt5-translations
yay -S rav1e
yay -S rclone
yay -S rclone-browser
yay -S re2
yay -S readline
yay -S ripgrep
yay -S rofi
yay -S run-parts
yay -S sbc
yay -S sddm-git
yay -S sdl2
yay -S seatd
yay -S sed
yay -S serd
yay -S shadow
yay -S shared-mime-info
yay -S slang
yay -S snappy
yay -S sndio
yay -S sord
yay -S spdlog
yay -S speex
yay -S speexdsp
yay -S sqlite
yay -S sratom
yay -S srt
yay -S startup-notification
yay -S sudo
yay -S svt-av1
yay -S systemd
yay -S systemd-libs
yay -S systemd-sysvcompat
yay -S taglib
yay -S tar
yay -S texinfo
yay -S tinycompress
yay -S tpm2-tss
yay -S tracker3
yay -S tslib
yay -S ttf-liberation
yay -S twolame
yay -S tzdata
yay -S upower
yay -S usbmuxd
yay -S util-linux
yay -S util-linux-libs
yay -S v4l-utils
yay -S vi
yay -S vid.stab
yay -S visual-studio-code-bin
yay -S vmaf
yay -S vulkan-headers
yay -S vulkan-icd-loader
yay -S vulkan-validation-layers
yay -S wavpack
yay -S waybar-hyprland-git
yay -S wayland
yay -S wayland-protocols
yay -S webkit2gtk
yay -S webrtc-audio-processing
yay -S wev-git
yay -S which
yay -S wildmidi
yay -S wine
yay -S wireplumber
yay -S woff2
yay -S wpa_supplicant
yay -S wpebackend-fdo
yay -S x264
yay -S x265
yay -S xcb-proto
yay -S xcb-util
yay -S xcb-util-cursor
yay -S xcb-util-errors
yay -S xcb-util-image
yay -S xcb-util-keysyms
yay -S xcb-util-renderutil
yay -S xcb-util-wm
yay -S xcb-util-xrm
yay -S xdg-dbus-proxy
yay -S xdg-utils
yay -S xf86-input-libinput
yay -S xkeyboard-config
yay -S xorg-fonts-encodings
yay -S xorg-server
yay -S xorg-server-common
yay -S xorg-setxkbmap
yay -S xorg-xauth
yay -S xorg-xinput
yay -S xorg-xkbcomp
yay -S xorg-xprop
yay -S xorg-xrandr
yay -S xorg-xset
yay -S xorg-xwayland
yay -S xorgproto
yay -S xvidcore
yay -S xz
yay -S yajl
yay -S yay
yay -S zeromq
yay -S zimg
yay -S zlib
yay -S zram-generator
yay -S zstd
yay -S zziplib
